export { https } from './src/main/ets/apis/HttpApis';

export { httpsMock } from './src/main/ets/mocks/HttpApisMock';

export { GetAttractionDetailResp } from './src/main/ets/types/responseTypes/GetAttractionDetailResp';

export { GetBulletinDetailResp } from './src/main/ets/types/responseTypes/GetBulletinDetailResp';

export { GetTicketDetailResp } from './src/main/ets/types/responseTypes/GetTicketDetailResp';

export { GetBulletinListResp } from './src/main/ets/types/responseTypes/GetBulletinListResp';

export { GetAttractionsInfoResp, AttractionListItem } from './src/main/ets/types/responseTypes/GetAttractionListResp';

export { GetHomeInfoResp, WeatherType, AtmosphereType } from './src/main/ets/types/responseTypes/GetHomeRollUpInfoResp';

export { GetTicketListResp } from './src/main/ets/types/responseTypes/GetTicketListResp';

export { GetTicketOrderListResp, TicketOrderListItem } from './src/main/ets/types/responseTypes/GetTicketOrderListResp';

export { GetAddressListResp } from './src/main/ets/types/responseTypes/GetAddressListResp';

export { GetTouristListResp } from './src/main/ets/types/responseTypes/GetTouristListResp';

export { MockResourceEnum } from './src/main/ets/mocks/MockResourceEnum';

export { CreateTicketOrderRequest,
  TouristRequest,
  GetOrderDetailRequest,
  AddressRequest } from './src/main/ets/types/AxiosRequestParam';

export { BaseResponse, GetUserInfoResp } from './src/main/ets/types/ResponseTypes';

export { mapperAttractionsInfo } from './src/main/ets/mapper/Index';